### ISSUE TITLE
Typo in sensors.yaml

### ISSUE THREAD

**Issue by bbostock** [ronschaeffer/sbm2mqtt#1]
Hi Ron, 
In sensors.yaml, the mqtt name for battery is suffixed temperature.
Cheers, 
Bill

**Comment by ronschaeffer** [comment]
Fixed. Thanks!

**Comment by atcapollo** [comment]
Same issue in the readme text.

**Comment by ronschaeffer** [comment]
@atcapollo Thanks, fixed.
