### ISSUE TITLE
Switchbot meter

### ISSUE THREAD

**Issue by hamdanfadi** [ronschaeffer/sbm2mqtt#14]
Hi there,
I’m using py Switchbot MQTT In my Raspberry pi 4b. It works fine. Can I install this library on the same machine? Is there any problem? Does it conflict with Switchbot MQTT?

**Comment by ronschaeffer** [comment]
The MQTT side would be fine. 

However, I have not managed to get the Bluetooth side to run properly on a Pi 4, including also in Docker. You could try it and see if you have more luck. If you do manage to get it running on a Pi 4, I'd love to hear how you did it.

**Comment by hamdanfadi** [comment]
Yeeeeees it is working

**Comment by ronschaeffer** [comment]
Good to hear! Did you do anything differently on the Pi 4 than what I described in the instructions? Maybe I'll have to try a different Pi 4.

**Comment by hamdanfadi** [comment]
No same instructions by the way o have 4B

**Comment by ronschaeffer** [comment]
Great, thanks. I'll give it another try on a different Pi 4B.

**Comment by ronschaeffer** [comment]
Just got it working first time on a different Pi 4.

**Comment by hamdanfadi** [comment]
Awesome! I should have a gift from you 😬

On 19/03/2021, at 03:51, Ron Schaeffer ***@***.***> wrote:

﻿

Just got it working first time on a different Pi 4.
