### ISSUE TITLE
Unraid support, upload dockerfile to docker hub

### ISSUE THREAD

**Issue by Frooodle** [ronschaeffer/sbm2mqtt#19]
Is there any chance you can upload the dockerfile here to dockerhub so that i can integrate it with my unraid server and their "apps" menu?

**Comment by ronschaeffer** [comment]
Sorry for the very slow reply. I'm no longer maintaining this project, because the official Home Assistant Switchbot integration now supports meters, See https://www.home-assistant.io/integrations/switchbot/ if you haven't already.
