### ISSUE TITLE
No meter found

### ISSUE THREAD

**Issue by atcapollo** [ronschaeffer/sbm2mqtt#2]
Unfortunately not working for me.

I've followed the install instructions and have tried scanning for my Switchbot Meter v2.5 in both pairing and normal mode.

The switchbot app picks it up. 
The RPi0 W can see it with hcitool lescan.

The script puts out:

sudo python3 sbm2mqtt.py

Scanning for SwitchBot Meters...

Finished.

Any way to debug this further?
Does the switchbot meter need to be pre paired with the RPi 0 W?

**Comment by atcapollo** [comment]
Now working after installing sudo pip3 install pexpect

But errors as below:

```
sudo python3 sbm2mqtt.py

Scanning for SwitchBot Meters...

fe:b8:36:f2:79:29 @ 2020-03-29 21:39:54
Traceback (most recent call last):
  File "sbm2mqtt.py", line 114, in <module>
    main()
  File "sbm2mqtt.py", line 108, in main
    scanner.scan(10.0)
  File "/usr/local/lib/python3.4/dist-packages/bluepy/btle.py", line 853, in scan
    self.process(timeout)
  File "/usr/local/lib/python3.4/dist-packages/bluepy/btle.py", line 842, in process
    self.delegate.handleDiscovery(dev, (dev.updateCount <= 1), isNewData)
  File "sbm2mqtt.py", line 73, in handleDiscovery
    print("  Temp: " + str(temperature) + "\xb0" + temp_scale)
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 12: ordinal not in range(128)

```

**Comment by atcapollo** [comment]
Python3 clearly doesn't like "\xb0" which I assume is the degree symbol.

**Comment by ronschaeffer** [comment]
Hi, thanks for trying it out, @atcapollo. The issue with the "\xb0" (yes, the degree symbol) appears to be one of character set.

I've made a new commit to sbm2mqtt.py which specifies UTF-8 and uses the actual degree symbol instead of the escape code for it. Please let me know if it now works for you.

The pexpect module issue is perplexing. The script doesn't import from the pexpect module, and pexpect is not installed on the Pi I'm using for testing. I just checked again:

```
pi@PISTUDY:~/switchbot $ sudo pip3 uninstall pexpect
Skipping pexpect as it is not installed.
```
Would you mind trying: 
```
sudo pip3 uninstall pexpect
```
and executing the script again to see what happens? You can always reinstall pexpect after.

Thanks.

**Comment by atcapollo** [comment]
Seems to work without pexpect. Not sure what happened there.

Still same character coding issue:


`Scanning for SwitchBot Meters...

fe:b8:36:f2:79:29 @ 2020-04-10 12:25:20
Traceback (most recent call last):
  File "/usr/local/switchbot/sbm2mqtt.py", line 115, in <module>
    main()
  File "/usr/local/switchbot/sbm2mqtt.py", line 109, in main
    scanner.scan(10.0)
  File "/usr/local/lib/python3.4/dist-packages/bluepy/btle.py", line 853, in scan
    self.process(timeout)
  File "/usr/local/lib/python3.4/dist-packages/bluepy/btle.py", line 842, in process
    self.delegate.handleDiscovery(dev, (dev.updateCount <= 1), isNewData)
  File "/usr/local/switchbot/sbm2mqtt.py", line 74, in handleDiscovery
    print("  Temp: " + str(temperature) + "\xb0 " + temp_scale)
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 12: ordinal not in range(128)`

**Comment by ronschaeffer** [comment]
OK, I've changed the way the degree symbol is represented in the code again:

`print("  Temp: " + str(temperature) + "\u00B0" + temp_scale)`

Please try the latest version. Fingers crossed.
