### ISSUE TITLE
Updating HA to 2022.06 breaks the configuration

### ISSUE THREAD

**Issue by turbatus** [ronschaeffer/sbm2mqtt#23]
Hi,
I have update HA to 2022.06 and changed the mqtt yaml configuration according to the new layout requirements (see first point of Breaking changes in the [release notes](https://www.home-assistant.io/blog/2022/06/01/release-20226/#breaking-changes))
Using the old one works as expected.

**Comment by kbarendrecht** [comment]
@turbatus it seems to work fine for me, i implemented it as such: https://github.com/ronschaeffer/sbm2mqtt/pull/24

**Comment by turbatus** [comment]
Thank you.
