### ISSUE TITLE
No Meters Found

### ISSUE THREAD

**Issue by Captain0Kangaroo** [ronschaeffer/sbm2mqtt#28]
Just installed onto my Pi Zero 2 W and im not seeing any meters. (The Pi is about 4 feet away from the Switchbot Temp).

I just get this:

**pi@respberrypizero:~/switchbot $ sudo python3 sbm2mqtt.py

Scanning for SwitchBot Meters...

Finished.**

Any ideas why this might be the case?

**Comment by ronschaeffer** [comment]
Sorry for the slow reply. I'm no longer maintaining this project, because the official Home Assistant Switchbot integration now supports meters, See https://www.home-assistant.io/integrations/switchbot/ if you haven't already.
