### ISSUE TITLE
Triggers in Home Assistant

### ISSUE THREAD

**Issue by GreenBear33** [ronschaeffer/sbm2mqtt#5]
Hi Ron, 

Thanks again for helping get the switchbot meters to be visible in Home Assistant. It is working perfectly. 

I am currently setting up some automation but I am struggling to get switches to trigger when the temperature or humidity changes and I was hoping you could help me.

I am trying to use the numeric state trigger. I am sure the switches work within the automation but home assistant does not read the numeric state of the switchbots. Should I use the MQTT trigger? and if so how to I get it to trigger above or below a certain value?

Hope you can help. have a great day.

**Comment by GreenBear33** [comment]
Solution Found.

**Comment by ronschaeffer** [comment]
Glad you got it working. I would have said that numeric state should work.
