### ISSUE TITLE
Python package 

### ISSUE THREAD

**Issue by Bas-Man** [ronschaeffer/sbm2mqtt#9]
Hi,

Great work on the script. Just got it working today. I have actually been looking for something for a while. 

I was wondering if you have given any thought to making a package for the SwitchBot portion.

**Comment by ronschaeffer** [comment]
Sorry for the delay in replying. I haven't thought about creating a Python package, but please feel free if you'd like to. Out of curiosity, what is your use case? I did recently add an option to use Docker as a simpler installation method.

**Comment by Bas-Man** [comment]
Hi. Sorry for my own lack of a replay. Just saw it now.
For my own use case I have three switch sensors. 
The use case I had in mind was to have the code made into a package for someone to possibly use to create a native addon for home assistant.
